events {}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    # 将 server 指令放在 http 块内
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri /index.html;
        }
    }
}